// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yznyhcoegtcknwydkqbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bnloY29lZ3Rja253eWRrcWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTk5NjksImV4cCI6MjA2MTE3NTk2OX0.wHTwcWVEFT4aQPvfrucgy0fWwH7VF4SzHoknjeVWna0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);